#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MaskedEditText.Sample.Resource", IsApplication=true)]

namespace MaskedEditText.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MaskedEditText.Resource.Attribute.CharRepresentation = global::MaskedEditText.Sample.Resource.Attribute.CharRepresentation;
			global::MaskedEditText.Resource.Attribute.Mask = global::MaskedEditText.Sample.Resource.Attribute.Mask;
			global::MaskedEditText.Resource.Attribute.MaskFill = global::MaskedEditText.Sample.Resource.Attribute.MaskFill;
			global::MaskedEditText.Resource.Styleable.MaskedEditText = global::MaskedEditText.Sample.Resource.Styleable.MaskedEditText;
			global::MaskedEditText.Resource.Styleable.MaskedEditText_CharRepresentation = global::MaskedEditText.Sample.Resource.Styleable.MaskedEditText_CharRepresentation;
			global::MaskedEditText.Resource.Styleable.MaskedEditText_Mask = global::MaskedEditText.Sample.Resource.Styleable.MaskedEditText_Mask;
			global::MaskedEditText.Resource.Styleable.MaskedEditText_MaskFill = global::MaskedEditText.Sample.Resource.Styleable.MaskedEditText_MaskFill;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int CharRepresentation = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int Mask = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int MaskFill = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MaskedEditText = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int MaskedEditText_CharRepresentation = 2;
			
			// aapt resource value: 0
			public const int MaskedEditText_Mask = 0;
			
			// aapt resource value: 1
			public const int MaskedEditText_MaskFill = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
